#!/bin/sh

# are there any conflicted/nonupgraded packages? (print last line only if it contains non-zero number)
apt-get --dry-run dist-upgrade | sed -ne '$s/^\(.*[1-9].*\)$/\1/p' > /var/spool/nagios-local-multi/apt

# update timestamp file always
echo "OK: `date`" > /var/spool/nagios-local-multi/timestamp.tmp && mv -f /var/spool/nagios-local-multi/timestamp.tmp /var/spool/nagios-local-multi/timestamp

# last apt update timestamp
test -f /var/lib/apt/periodic/update-stamp && cp -pf /var/lib/apt/periodic/update-stamp /var/spool/nagios-local-multi/apt_update_sucess_timestamp
test -f /var/lib/apt/periodic/update-success-stamp && cp -pf /var/lib/apt/periodic/update-success-stamp /var/spool/nagios-local-multi/apt_update_sucess_timestamp

# check for finished no-systemd instalation
dpkg -l tomsoft-sysv 2>/dev/null | grep -q '^ii' && dpkg -l systemd systemd-sysv dbus 2>/dev/null | awk '/^i./ { print $2} ' | xargs -r echo "WARNING: do: apt-get remove --purge" > /var/spool/nagios-local-multi/no_systemd_timestamp

# console setting unwanted for servers
dpkg -l console-setup console-setup-linux kbd keyboard-configuration xkb-data 2>/dev/null | awk '/^i./ { print $2} ' | xargs -r echo "WARNING: do: apt-get remove --purge" > /var/spool/nagios-local-multi/no_kbd

exit 0
