#!/bin/sh

# are there any conflicted/nonupgraded packages? (print last line only if it contains non-zero number)
apt-get --dry-run dist-upgrade | sed -ne '$s/^\(.*[1-9].*\)$/\1/p' > /var/spool/nagios-local-multi/apt

